### ISSUE TITLE
Possible bug: should the margin-header image reference link be relative/local rather than global/https ?

### ISSUE THREAD

**Issue by mh0w** [datasciencecampus/coding-in-the-open#67]
**Describe the bug**
Sorry if I'm not describing the possible bug very well. Grateful for any thoughts on why I encountered this issue while others (presumably) did not.

I cloned the coding-in-the-open repo and found that I could not render or preview. When trying to do so, I'd get the following error message:

```
PS C:\Users\hawkem\coding-in-the-open> quarto render
ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat '<a href="https://datasciencecampus.ons.gov.uk/">
  <img src="https://datasciencecampus.ons.gov.uk/wp-content/uploads/sites/10/2017/03/data-science-campus-logo-new.svg" alt="Data Science Campus logo">
</a>
'

Error: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat '<a href="https://datasciencecampus.ons.gov.uk/">
  <img src="https://datasciencecampus.ons.gov.uk/wp-content/uploads/sites/10/2017/03/data-science-campus-logo-new.svg" alt="Data Science Campus logo">
</a>
'
    at Object.lstatSync (deno:runtime/js/30_fs.js:305:9)
    at existsSync (file:///C:/Program%20Files/Quarto/bin/quarto.js:492:14)
    at resolveProjectPaths (file:///C:/Program%20Files/Quarto/bin/quarto.js:83448:13)
    at Array.map (<anonymous>)
    at Object.websiteProjectConfig [as config] (file:///C:/Program%20Files/Quarto/bin/quarto.js:83455:73)
    at projectContext (file:///C:/Program%20Files/Quarto/bin/quarto.js:82789:48)
    at async render (file:///C:/Program%20Files/Quarto/bin/quarto.js:90657:21)
    at async Command.fn (file:///C:/Program%20Files/Quarto/bin/quarto.js:90856:32)
    at async Command.execute (file:///C:/Program%20Files/Quarto/bin/quarto.js:8437:13)
    at async quarto (file:///C:/Program%20Files/Quarto/bin/quarto.js:127545:5)
PS C:\Users\hawkem\coding-in-the-open>
```

I was able to resolve this issue in my case by downloading the data-science-campus-logo-new.svg image to the ../assets/image folder and then changing the image reference in _quarto.yml like so:

```yml
# How it was before:
  margin-header: |
    <a href="https://datasciencecampus.ons.gov.uk/">
      <img src="https://datasciencecampus.ons.gov.uk/wp-content/uploads/sites/10/2017/03/data-science-campus-logo-new.svg" alt="Data Science Campus logo">
    </a>

# The new version:
  margin-header: |
    ![Data Science Campus logo](/assets/images/data-science-campus-logo-new.svg)
```

After implementing this change, I find I can render normally:

```
PS C:\Users\hawkem\coding-in-the-open> quarto render
[ 1/10] CONTRIBUTING.md
Sending fatal alert BadCertificate
[ 2/10] general-considerations\guidance.qmd
[ 3/10] general-considerations\references.qmd
[ 4/10] index.qmd
[ 5/10] never-open\guidance.qmd
[ 6/10] open-at-the-end\guidance.qmd
[ 7/10] open-at-the-end\process-chart.qmd
[ 8/10] open-at-the-end\risk-table.qmd
[ 9/10] open-at-the-start\guidance.qmd
[10/10] what-could-go-wrong\checklist.qmd

Output created: docs\index.html
```

**To Reproduce**
1. Clone coding-in-the-open repo (main branch)
2. Try to `quarto render`
3. See error

**Expected behavior**
I expect quarto to render successfully, but it does not unless I implement the change I describe above.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: not sure this is relevant here, but Chrome 115.0.5790.171
